apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        myapp.microservice: back-app
    spec:
      containers:
      - env:
        - name: SOCKET_SERVER_PORT
          value: "9000"
        image: pabloborh/workshop-back:v1
        imagePullPolicy: Always
        name: back-pod
        resources: 
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            memory: "512Mi"
      restartPolicy: Always
