apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-deploy-v2
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        myapp.microfront: front-app.v2
    spec:
      containers:
      - env:
        - name: BACKEND_ENDPOINT
          value: http://my-back:80
        - name: WEB_PORT
          value: "8080"
        image: pabloborh/workshop-front:v2
        imagePullPolicy: Always
        name: front-pod
        resources: 
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            memory: "512Mi"
      restartPolicy: Always
